---
- name: Configure host
  hosts: all

  vars_files:
    - default.config.yml
  
  pre_tasks:
    - name: Include playbook override configuration
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir}}/config.yml"
      tags: ['always']

  roles:
    - role: geerlingguy.mac.homebrew
      tags: [homebrew]
    - role: geerlingguy.mac.dock
      tags: [dock]

  tasks:
    - import_tasks: tasks/vs_code.yml
      when: configure_vscode
    
    - import_tasks: tasks/git.yml
      when: configure_git