---
- name: Git | Set global username
  ansible.builtin.git_config:
    name: user.name
    scope: global
    value: "{{ git_global_username }}"

- name: Git | Set global email
  ansible.builtin.git_config:
    name: user.email
    scope: global
    value: "{{ git_global_email }}"

- name: Git | Alias for commit
  ansible.builtin.git_config:
    name: alias.ci
    scope: global
    value: commit

- name: Git | Alias for status
  ansible.builtin.git_config:
    name: alias.st
    scope: global
    value: status

- name: Git | Add git user in ssh_config for typical services
  community.general.ssh_config:
    user: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_gid }}"
    remote_user: git
    host: "{{ item }}"
  loop:
    - github.com
    - gitlab.com
  
- name: "Git | Ensure the directory exists for repos"
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_gid }}"
    state: directory
  loop: "{{ git_sub_configs }}"

- name: "Git | Create config stubs"
  ansible.builtin.template:
    src: files/git/.gitconfig.j2
    dest: "{{item.path}}/.gitconfig-{{item.config_name}}"
  loop: "{{ git_sub_configs }}"

- name: "Git | Add the includeIf block in the .gitconfig for {{ item.path }}"
  ansible.builtin.blockinfile:
    path: ~/.gitconfig
    block: |
      {% for item in git_sub_configs %}
      [includeIf "gitdir:{{item.path}}/"]
        path = {{item.path}}/.gitconfig-{{item.config_name}}
      {% endfor %}