---
- name: Git | Set global username
  ansible.builtin.git_config:
    name: user.name
    scope: global
    value: "{{ git_config_username }}"

- name: Git | Set global email
  ansible.builtin.git_config:
    name: user.email
    scope: global
    value: "{{ git_config_email }}"

- name: Git | Alias for commit
  ansible.builtin.git_config:
    name: alias.ci
    scope: global
    value: commit

- name: Git | Alias for status
  ansible.builtin.git_config:
    name: alias.st
    scope: global
    value: status

- name: Git | Add git user in ssh_config for typical services
  community.general.ssh_config:
    user: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_gid }}"
    remote_user: git
    host: "{{ item }}"
  loop:
    - github.com
    - gitlab.com